# Generated by Django 5.1.1 on 2024-09-25 05:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, unique=True, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, unique=True, verbose_name='Название района')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип')),
                ('address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('private', models.BooleanField(default=True, verbose_name='Предприятие является частным агентством занятости')),
                ('activity', models.CharField(blank=True, choices=[('13', 'Сельское хозяйство'), ('1', 'Производство'), ('2', 'Торговля'), ('3', 'Сфера услуг'), ('4', 'Образование'), ('5', 'Здравоохранение'), ('6', 'ИТ и телекоммуникации'), ('7', 'Строительство'), ('8', 'Транспорт и логистика'), ('9', 'Финансы и страхование'), ('10', 'Наука и исследования'), ('11', 'Искусство и культура'), ('12', 'Государственная служба')], max_length=2, null=True, verbose_name='Вид деятельности')),
                ('own', models.CharField(blank=True, choices=[('1', 'Государственная собственность'), ('2', 'Иностранная собственность'), ('3', 'Частная собственность'), ('4', 'Муниципальная собственность'), ('5', 'Собственность общественных организаций'), ('6', 'Совместная собственность'), ('7', 'Акционерная собственность')], max_length=1, null=True, verbose_name='Форма собственности')),
                ('contact', models.CharField(max_length=255, verbose_name='Контактные данные')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram номер или @Name')),
                ('web_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='URL веб сайта')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='whatsapp номер')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('enlarge_view', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организаци',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Загаловак')),
                ('title_info', models.CharField(max_length=150, verbose_name='Под загаловок')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработная плата')),
                ('experience', models.CharField(blank=True, choices=[('1', 'Без опыта'), ('2', 'От 1 до 3 лет'), ('3', 'От 3 до 5 лет'), ('4', 'Более 5 лет'), ('5', 'Стажировка'), ('6', 'Волонтерский опыт'), ('7', 'Производственная практика')], max_length=1, null=True, verbose_name='Опыт работы')),
                ('schedule', models.CharField(blank=True, choices=[('1', 'Полный рабочий день'), ('2', 'Неполный рабочий день'), ('3', 'Частичная занятость'), ('4', 'Удаленная работа'), ('5', 'Надомная работа'), ('6', 'Гибкий график'), ('7', 'Посменный'), ('8', 'Свободный график'), ('9', 'Вахтовый метод')], max_length=1, null=True, verbose_name='График работы')),
                ('type_of_work', models.CharField(blank=True, choices=[('1', 'Строительство'), ('2', 'Дворник'), ('3', 'Сантехник'), ('4', 'Электрик'), ('5', 'Слесарь'), ('6', 'Маляр'), ('7', 'Каменщик'), ('8', 'Уборщик'), ('9', 'Плотник'), ('10', 'Грузчик'), ('11', 'Монтажник'), ('12', 'Кровельщик'), ('13', 'Водитель'), ('14', 'Штукатур'), ('15', 'Столяр'), ('16', 'Сварщик'), ('17', 'Токарь'), ('18', 'Плиточник'), ('19', 'Разнорабочий'), ('20', 'Машинист')], max_length=2, null=True, verbose_name='Тип работы')),
                ('number_persons', models.IntegerField(verbose_name='Количество необходимых человек')),
                ('data_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('enlarge_view', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.area', verbose_name='Район')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.city', verbose_name='Город')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакасию',
                'verbose_name_plural': 'Отклики на вакасию',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинга')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', through='jobs.Review', to=settings.AUTH_USER_MODEL, verbose_name='Отзывы'),
        ),
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ключевые навык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Навык пользователя',
                'verbose_name_plural': 'Навыки пользователя',
            },
        ),
    ]
